# ./override_files/postgres_values.yaml

image:
  registry: docker.io
  repository: bitnamilegacy/postgresql
  tag: "16.6.0-debian-12-r2"
  pullPolicy: IfNotPresent

auth:
  enablePostgresUser: true
  postgresPassword: "MySuperSecurePassword123!"

